spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: friendchise
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME:root}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
  data:
    jpa:
      auditing:
        enabled: false
    redis:
      host: 13.209.82.1
      port: 6379
      password: ${REDIS_PASSWORD}
